## Importing Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = (10,5)
plt.rcParams['figure.dpi'] = 250
import seaborn as sns
sns.set_theme(style='darkgrid',palette='rainbow')
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split,GridSearchCV

## Importing Dataset

In [2]:
train = pd.read_csv(r"C:\Users\umair\OneDrive\Desktop\My Files\ExcelR\Assignments\Support Vector Machines\SalaryData_Train(1).csv")
test = pd.read_csv(r"C:\Users\umair\OneDrive\Desktop\My Files\ExcelR\Assignments\Support Vector Machines\SalaryData_Test(1).csv")

## Data Analysis

In [3]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30161 entries, 0 to 30160
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            30161 non-null  int64 
 1   workclass      30161 non-null  object
 2   education      30161 non-null  object
 3   educationno    30161 non-null  int64 
 4   maritalstatus  30161 non-null  object
 5   occupation     30161 non-null  object
 6   relationship   30161 non-null  object
 7   race           30161 non-null  object
 8   sex            30161 non-null  object
 9   capitalgain    30161 non-null  int64 
 10  capitalloss    30161 non-null  int64 
 11  hoursperweek   30161 non-null  int64 
 12  native         30161 non-null  object
 13  Salary         30161 non-null  object
dtypes: int64(5), object(9)
memory usage: 3.2+ MB


In [4]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15060 entries, 0 to 15059
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   age            15060 non-null  int64 
 1   workclass      15060 non-null  object
 2   education      15060 non-null  object
 3   educationno    15060 non-null  int64 
 4   maritalstatus  15060 non-null  object
 5   occupation     15060 non-null  object
 6   relationship   15060 non-null  object
 7   race           15060 non-null  object
 8   sex            15060 non-null  object
 9   capitalgain    15060 non-null  int64 
 10  capitalloss    15060 non-null  int64 
 11  hoursperweek   15060 non-null  int64 
 12  native         15060 non-null  object
 13  Salary         15060 non-null  object
dtypes: int64(5), object(9)
memory usage: 1.6+ MB


In [5]:
train.describe()

age   educationno   capitalgain   capitalloss  hoursperweek
count  30161.000000  30161.000000  30161.000000  30161.000000  30161.000000
mean      38.438115     10.121316   1092.044064     88.302311     40.931269
std       13.134830      2.550037   7406.466611    404.121321     11.980182
min       17.000000      1.000000      0.000000      0.000000      1.000000
25%       28.000000      9.000000      0.000000      0.000000     40.000000
50%       37.000000     10.000000      0.000000      0.000000     40.000000
75%       47.000000     13.000000      0.000000      0.000000     45.000000
max       90.000000     16.000000  99999.000000   4356.000000     99.000000

In [6]:
test.describe()

age   educationno   capitalgain   capitalloss  hoursperweek
count  15060.000000  15060.000000  15060.000000  15060.000000  15060.000000
mean      38.768327     10.112749   1120.301594     89.041899     40.951594
std       13.380676      2.558727   7703.181842    406.283245     12.062831
min       17.000000      1.000000      0.000000      0.000000      1.000000
25%       28.000000      9.000000      0.000000      0.000000     40.000000
50%       37.000000     10.000000      0.000000      0.000000     40.000000
75%       48.000000     13.000000      0.000000      0.000000     45.000000
max       90.000000     16.000000  99999.000000   3770.000000     99.000000

In [7]:
train.isnull().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [8]:
test.isnull().sum()

age              0
workclass        0
education        0
educationno      0
maritalstatus    0
occupation       0
relationship     0
race             0
sex              0
capitalgain      0
capitalloss      0
hoursperweek     0
native           0
Salary           0
dtype: int64

In [9]:
le = LabelEncoder()

In [10]:
train= train.apply(LabelEncoder().fit_transform)
train

age  workclass  education  educationno  maritalstatus  occupation  \
0       22          5          9           12              4           0   
1       33          4          9           12              2           3   
2       21          2         11            8              0           5   
3       36          2          1            6              2           5   
4       11          2          9           12              2           9   
...    ...        ...        ...          ...            ...         ...   
30156   10          2          7           11              2          12   
30157   23          2         11            8              2           6   
30158   41          2         11            8              6           0   
30159    5          2         11            8              4           0   
30160   35          3         11            8              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 1     4    1           24            0            39   
1                 0     4    1            0            0            12   
2                 1     4    1            0            0            39   
3                 0     2    1            0            0            39   
4                 5     2    0            0            0            39   
...             ...   ...  ...          ...          ...           ...   
30156             5     4    0            0            0            37   
30157             0     4    1            0            0            39   
30158             4     4    0            0            0            39   
30159             3     4    1            0            0            19   
30160             5     4    0          107            0            39   

       native  Salary  
0          37       0  
1          37       0  
2          37       0  
3          37       0  
4           4       0  
...       ...     ...  
30156      37       0  
30157      37       1  
30158      37       0  
30159      37       0  
30160      37       1  

[30161 rows x 14 columns]

In [11]:
test= test.apply(LabelEncoder().fit_transform)
test

age  workclass  education  educationno  maritalstatus  occupation  \
0        8          2          1            6              4           6   
1       21          2         11            8              2           4   
2       11          1          7           11              2          10   
3       27          2         15            9              2           6   
4       17          2          0            5              4           7   
...    ...        ...        ...          ...            ...         ...   
15055   16          2          9           12              4           9   
15056   22          2          9           12              0           9   
15057   21          2          9           12              2           9   
15058   27          2          9           12              0           0   
15059   18          3          9           12              2           3   

       relationship  race  sex  capitalgain  capitalloss  hoursperweek  \
0                 3     2    1            0            0            39   
1                 0     4    1            0            0            49   
2                 0     4    1            0            0            39   
3                 0     2    1           87            0            39   
4                 1     4    1            0            0            29   
...             ...   ...  ...          ...          ...           ...   
15055             3     4    1            0            0            39   
15056             1     4    0            0            0            35   
15057             0     4    1            0            0            49   
15058             3     1    1           73            0            39   
15059             0     4    1            0            0            59   

       native  Salary  
0          37       0  
1          37       0  
2          37       1  
3          37       1  
4          37       0  
...       ...     ...  
15055      37       0  
15056      37       0  
15057      37       0  
15058      37       0  
15059      37       1  

[15060 rows x 14 columns]

In [12]:
xtrain = train.drop(['maritalstatus','sex','native','race','relationship','Salary'],axis=1).values
ytrain = train['Salary'].values

In [13]:
xtrain

array([[ 22,   5,   9, ...,  24,   0,  39],
       [ 33,   4,   9, ...,   0,   0,  12],
       [ 21,   2,  11, ...,   0,   0,  39],
       ...,
       [ 41,   2,  11, ...,   0,   0,  39],
       [  5,   2,  11, ...,   0,   0,  19],
       [ 35,   3,  11, ..., 107,   0,  39]], dtype=int64)

In [14]:
ytrain

array([0, 0, 0, ..., 0, 0, 1])

In [15]:
xtest = test.drop(['maritalstatus','sex','native','race','relationship','Salary'],axis=1).values
ytest = test['Salary'].values

In [16]:
xtest

array([[ 8,  2,  1, ...,  0,  0, 39],
       [21,  2, 11, ...,  0,  0, 49],
       [11,  1,  7, ...,  0,  0, 39],
       ...,
       [21,  2,  9, ...,  0,  0, 49],
       [27,  2,  9, ..., 73,  0, 39],
       [18,  3,  9, ...,  0,  0, 59]], dtype=int64)

In [17]:
ytest

array([0, 0, 1, ..., 0, 0, 1])

In [18]:
columns=["age","workclass","education","educationno","maritalstatus","occupation","relationship","race","sex","capitalgain","capitalloss","hoursperweek","native","Salary"]

In [19]:
number = LabelEncoder()
for i in columns:
    train[i] = number.fit_transform(train[i])
    test[i] = number.fit_transform(test[i])

colnames = train.columns

In [20]:
trainx = train[colnames[0:13]]
trainy = train[colnames[13]]
testx = test[colnames[0:13]]
testy  = test[colnames[13]]

In [21]:
def norm_func(i):
    x = (i-i.min())/(i.max()-i.min())
    return (x)

In [22]:
trainx = norm_func(trainx)
testx =  norm_func(testx)

## Model Building

In [23]:
svm = SVC(kernel = "linear")
svm.fit(trainx,trainy)
ypred= svm.predict(testx)
print(classification_report(testy,ypred))

              precision    recall  f1-score   support

           0       0.81      0.97      0.88     11360
           1       0.75      0.30      0.43      3700

    accuracy                           0.80     15060
   macro avg       0.78      0.63      0.66     15060
weighted avg       0.79      0.80      0.77     15060



In [24]:
svm = SVC(kernel = "rbf",gamma="auto")
svm.fit(trainx,trainy)
ypred= svm.predict(testx)
print(classification_report(testy,ypred))

              precision    recall  f1-score   support

           0       0.85      0.94      0.89     11360
           1       0.74      0.49      0.59      3700

    accuracy                           0.83     15060
   macro avg       0.80      0.72      0.74     15060
weighted avg       0.82      0.83      0.82     15060



In [25]:
svm = SVC(kernel = "poly",gamma="auto")
svm.fit(trainx,trainy)
ypred= svm.predict(testx)
print(classification_report(testy,ypred))

              precision    recall  f1-score   support

           0       0.83      0.96      0.89     11360
           1       0.79      0.39      0.52      3700

    accuracy                           0.82     15060
   macro avg       0.81      0.68      0.71     15060
weighted avg       0.82      0.82      0.80     15060

